### ISSUE TITLE
Add ARM64 support

### ISSUE THREAD

**Issue by meyskens** [flatcar-linux/flatcar-linux-update-operator#64]
**Current situation**
Currently there are only amd64 builds available on quay.io.

**Impact**
Flatcar arm64 (alpha) users are not able to run FLUO.

**Ideal future situation**
There being amd64 and arm64 Docker images available.

**Comment by invidian** [comment]
Maybe could be done together with #65 :smile:

**Comment by Dhouti** [comment]
Any update on this? For now i've been able to just build it myself since everything seems arm64 compatible out of the box, but would love to be able to use a pre-built image.

**Comment by jepio** [comment]
@invidian how about we copy the approach from here: https://github.com/flatcar-linux/container-linux-config-transpiler/blob/flatcar-master/.github/workflows/docker.yml, that works quite well for publishing.

**Comment by invidian** [comment]
Thanks for suggestion @jepio I'll have a look and do some tests. This is something I'd like to address in the near future.
